# Settings schema.
enewsletters.settings:
  type: config_object
  label: 'Enewsletters settings'
  mapping:
    hash_expiration:
      type: integer
      label: Hash expiration
    newsletter:
      type: mapping
      label: Newsletter settings
      mapping:
        format:
          type: string
          label: Default format for new newsletters
        priority:
          type: integer
          label: Default priority for new newsletters
        from_address:
          type: string
          label: Default from email address
        from_name:
          type: label
          label: Default from name

# Newsletter issue field type schema.
field.storage_settings.newsletter_issue:
  type: field.storage_settings.entity_reference
  label: 'Newsletter issue settings'
  mapping: { }

field.field_settings.newsletter_issue:
  type: field.field_settings.entity_reference
  label: 'Newsletter issue settings'

field.value.newsletter_issue:
  type: field.value.entity_reference
  label: 'Default value'
  mapping:
    handler:
      type: string
      label: Handler
    handler_settings:
      type: mapping
      label: Handler settings
    status:
      type: integer
      label: Sent status
    sent_count:
      type: integer
      label: Sent count
