<?php
/**
 * @file
 * Contains admin_registration.module.
 */

/**
 * Implements hook_mail().
 * @param $key
 * @param $message
 * @param $params
 */
function admin_registration_mail($key, &$message, $params) {
  switch ($key) {
    case 'admin_reset':
      // Set the subject and body of the message.
      $message['subject'] = t('Account details for ' . $params['email'] . ' at New England Business Media');
      $messageBody = [
        '#theme' => 'admin_reset_password',
        '#url' => $params['url'],
      ];
      $mail_body = \Drupal::service('renderer')->render($messageBody);
      $message['body'][] = $mail_body;
      break;
  }
}

/**
 * Implements hook_theme().
 */
function admin_registration_theme($existing, $type, $theme, $path) {
  return [
    'admin_reset_password' => [
      'variables' => ['url' => NULL],
    ],
  ];
}